version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run:
          name: Build
          command: "dotnet build"
  test:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout
      - run:
          name: Test
          command: dotnet test PetfinderNet.Tests/PetfinderNet.Tests.csproj
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
